transfer file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,12 +1,27 @@
-#!/usr/bin/env bash
-# transfers a file from our client to a server
-
-if [ $# -lt 3 ];
-then
-	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY';
-elif [ $# -ge 4 ];
-then
-	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
-else
-	scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
-fi
+  1 #!/usr/bin/env bash
+  2 # checking for command line argument 
+  3 
+  4 if [ $# -lt 4 ]
+  5 then    
+  6         echo"usege: 0-transfer-file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  7         exit 1
+  8 fi      
+  9 
+ 10 # assigning paramentals to variables
+ 11 
+ 12 path_to_file=$1
+ 13 ip=$2
+ 14 username=$3
+ 15 path_to_ssh_key=$4
+ 16 
+ 17 # deaseblering strick host key checking 
+ 18 
+ 19 scp -o "stricthostkeycheking" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+ 20 
+ 21 # checking if the transfer is successful
+ 22 if [ $7 -eq 0]
+ 23 then
+ 24         echo"file was transfered successfully"
+ 25 else    
+ 26         echo"file transfer failed"
+ 27 fi
